Step 1: Import Required Libraries

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

Step-2: Load Dataset

In [3]:
pip install pandas numpy scikit-learn tensorflow openpyxl

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import pandas as pd

# Load dataset
file_path = "robot_dnn_training_data_18thMarch_V1.xlsx"

df = pd.read_excel(file_path, header=1)

print(df.head())
print(df.shape)

   Front (cm)  Left (cm)  Right (cm) Command
0        53.2       17.8         6.0       F
1        48.1       17.6         7.4       F
2        43.8       18.8         5.0       F
3        40.9       15.1         5.0       F
4        35.0       18.5         5.0       F
(10000, 4)


In [ ]:
print("Means:", scaler.mean_)
print("Std:", scaler.scale_)

In [5]:
# Features
X = df[['Front (cm)', 'Left (cm)', 'Right (cm)']]

# Target
y = df['Command']

In [6]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

print(encoder.classes_)

['B' 'F' 'L' 'R' 'S']


In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[ 3.14817947 -0.63245209 -1.04870399]
 [ 2.62527274 -0.63781484 -1.0064758 ]
 [ 2.18439059 -0.60563834 -1.07886699]
 ...
 [ 0.2670659  -0.65390308 -0.4032159 ]
 [-0.25584083 -0.36431462 -0.69579695]
 [ 0.63617654 -0.66462858 -0.48767229]]


In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y_encoded,
    test_size=0.2,
    random_state=42
)

In [9]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([

    keras.Input(shape=(3,)),

    layers.Dense(32, activation='relu'),

    layers.Dense(64, activation='relu'),

    layers.Dense(32, activation='relu'),

    layers.Dense(5, activation='softmax')

])

In [10]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [11]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 10s 13ms/step - accuracy: 0.8438 - loss: 0.6166 - val_accuracy: 0.9456 - val_loss: 0.1972
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9600 - loss: 0.1451 - val_accuracy: 0.9613 - val_loss: 0.1320
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9686 - loss: 0.1059 - val_accuracy: 0.9631 - val_loss: 0.1053
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9684 - loss: 0.0856 - val_accuracy: 0.9706 - val_loss: 0.0926
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9756 - loss: 0.0694 - val_accuracy: 0.9669 - val_loss: 0.0867
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.9775 - loss: 0.0613 - val_accuracy: 0.9744 - val_loss: 0.0668
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - accuracy: 0.9800 - loss: 0.0514 - val_accuracy: 0.9744 - val_loss: 0.0602
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.9797 - loss: 0.0495 - val_accu

In [12]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.9865 - loss: 0.0249  
Test Accuracy: 0.9865000247955322


In [17]:
print(encoder.classes_)

['B' 'F' 'L' 'R' 'S']


In [20]:
import numpy as np

sample = np.array([[5, 5, 5]])

sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))
print(command_index)

C:\Users\sdnis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step
Predicted Command: ['B']
0


In [21]:
import numpy as np

sample = np.array([[45, 25, 25]])

sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))
print(command_index)

C:\Users\sdnis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step
Predicted Command: ['F']
1


In [15]:
import numpy as np

sample = np.array([[5, 5, 50]]) 
sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))

C:\Users\sdnis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 370ms/step
Predicted Command: ['B']


In [16]:
import numpy as np

sample = np.array([[20, 5, 50]]) 
sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))

C:\Users\sdnis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step
Predicted Command: ['R']


In [ ]:
import numpy as np

sample = np.array([[-20, -55, -50]]) 
sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))

In [ ]:
model.save("robot_navigation_dnn.h5")

In [ ]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()

with open("robot_navigation_model.tflite", "wb") as f:
    f.write(tflite_model)

In [ ]:
sample = [[100, 50, 50]]

sample_scaled = scaler.transform(sample)

print(sample_scaled)

prediction = model.predict(sample_scaled)

print(prediction)
print(prediction.argmax())

In [ ]:
import numpy as np

sample = np.array([[20, 38, 200]]) 
sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))

In [ ]:
prediction = model.predict(sample_scaled)
print(prediction)

In [ ]:
import numpy as np

sample = np.array([[120, 38, 20]]) 
sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))
print(prediction)

In [ ]:
import numpy as np

sample = np.array([[20, 80, 20]]) 
sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))
print(prediction)

In [ ]:
import numpy as np

sample = np.array([[4, 8, 2]]) 
sample_scaled = scaler.transform(sample)

prediction = model.predict(sample_scaled)

command_index = prediction.argmax()

print("Predicted Command:", encoder.inverse_transform([command_index]))
print(prediction)

In [ ]:
sample = np.array([[4, 8, 2]])
sample_scaled = scaler.transform(sample)

print("Scaled:", sample_scaled)

prediction = model.predict(sample_scaled)
print("Predicted Command:", encoder.inverse_transform([command_index]))
print("Prediction:", prediction)
print("Argmax:", prediction.argmax())

In [ ]:
sample = np.array([[4, 8, 2]])
sample_scaled = scaler.transform(sample)

print("Scaled:", sample_scaled)

prediction = model.predict(sample_scaled)
print("Predicted Command:", encoder.inverse_transform([command_index]))

In [ ]:
print(encoder.classes_)

In [ ]:
pip install pydot graphviz

In [ ]:
pip uninstall pydotplus pydot -y

In [ ]:
pip install pydot

In [ ]:
import pandas as pd

# Load dataset
file_path = "robot_dnn_training_data_18thMarch_V1.xlsx"

df = pd.read_excel(file_path, header=1)

print(df.head())
print(df.shape)

In [ ]:
from tensorflow.keras.utils import plot_model

plot_model(
    model,
    to_file='dnn_structure.png',
    show_shapes=True,
    show_layer_names=True
)